accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'
urlpatterns = [
    path('singup/', views.UserRegister.as_view(), name='register'),
    path('singin/', views.UserLogin.as_view(), name='login'),
    path('singout/', views.UserLogout.as_view(), name='logout'),
    path('profile/<str:username>', views.UserDashboard.as_view(), name='dashboard'),
    path('dashboard/<str:username>/update/', views.UpdateUserProfile.as_view(), name='update_profile'),
    path('dashboard/<str:username>/pins', views.UserPins.as_view(), name='user_pins'),
    path('dashboard/pin/delete/<str:id>', views.DeletePinView.as_view(), name='delete_pin'),
    path('dashboard/<str:username>/newpin/', views.NewPinView.as_view(), name='new_pin'),
    path('dashboard/<str:username>/boards', views.UserBoards.as_view(), name='user_boards'),
    path('dashboard/<str:username>/newboard/', views.CreateBoardView.as_view(), name='newboard'),
    path('dashboard/photo/remove/' , views.RemovePhotoView.as_view(), name='remove_photo'),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('unfollow/', views.UnfollowView.as_view(), name='unfollow'),
    path('quicksave/<str:id>', views.QuickSaveView.as_view(), name='quicksave'),
    path('quicksave/remove/<str:id>', views.RemoveQuickSaveView.as_view(), name='remove_quicksave'),
    path('addtoboard/<str:pinid>/<str:boardid>', views.AddPinToBoard.as_view(), name='addtoboard'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pin.urls', namespace='pin')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pin/urls.py
from django.urls import path
from . import views

app_name = 'pin'

urlpatterns = [
    path('', views.PinsListView.as_view(), name='listpin'),
    path('pin/<slug:slug>/', views.PinView.as_view(), name='single_pin'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='photo', null=True, blank=True)
    age = models.IntegerField(blank=True, null=True)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.user}'

class UsersRelation(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return f'{self.from_user} following {self.to_user}'

accounts/forms.py
from django import forms
from .models import Profile
from pin.models import Pin, Board


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control mb-3'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control mb-3'}))



class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control mb-3'}))


class UpdateProfileForm(forms.ModelForm):
    first_name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    last_name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control mb-3'}))
    photo = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class': 'form-control mb-3'}))
    age = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'class': 'form-control mb-3'}))
    bio = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control mb-3','rows':3}))

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email', 'photo', 'age', 'bio')


class PinForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    board = forms.ModelChoiceField(queryset=Board.objects.all(), required=True, widget=forms.Select(attrs={'class': 'form-control mb-3'}))
    image = forms.ImageField(required=True, widget=forms.FileInput(attrs={'class': 'form-control mb-3'}))
    url = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    caption = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control mb-3','rows':3}))

    class Meta:
        model = Pin
        fields = ('title','board','image','url','caption')


class BoardForm(forms.ModelForm):
    title = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control mb-3'}))
    description = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control mb-3','rows':3}))

    class Meta:
        model = Board
        fields = ('title','description',)

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.views import View
from django.views.generic import DetailView
from .forms import UserRegistrationForm,UserLoginForm,UpdateProfileForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login , logout
from .models import Profile, UsersRelation
from django.contrib.auth.mixins import LoginRequiredMixin
from pin.models import Pin, Board, QuickSave
from .forms import PinForm,BoardForm
from django.http import JsonResponse




# All User Personal Info View
class UserRegister(View):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.create(username=cd['username'], email=cd['email'], password=cd['password'])
            profile = Profile(user=user)
            profile.save()
            messages.success(request, 'you singup successfully', 'info')
            return redirect('pin:listpin')
        return render(request, self.template_name, {'form':form})
            

class UserLogin(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'you singin successfully', 'info')
                return redirect('pin:listpin')
            messages.error(request, 'username or password is wrong', 'warning')
        return render(request, self.template_name, {'form':form})

class UserLogout(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'you singout from your accounts', 'info')
        return redirect('pin:listpin')


class UserDashboard(View):
    template_name = 'accounts/dashboard.html'
    
    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        userpins  = Pin.objects.filter(user=user)
        following = UsersRelation.objects.filter(from_user=user)
        followers = UsersRelation.objects.filter(to_user=user)
        self_dash = False
        is_following = False
        if request.user.is_authenticated:
            relation = UsersRelation.objects.filter(from_user=request.user, to_user=user)
            if relation.exists():
                is_following = True
        else:
            is_following = False
        
        if request.user.id == user.id:
            self_dash = True
        context = {
            'user':user,
            'userpins':userpins,
            'self_dash':self_dash,
            'is_following':is_following,
            'followers': followers,
            'following' : following,
            }
        return render(request, self.template_name, context)


class UpdateUserProfile(LoginRequiredMixin, View):
    template_name = 'accounts/update_profile.html'
    form_class = UpdateProfileForm

    def get(self, request, username):
        initial_dict = {"email" : request.user.email,"first_name" : request.user.first_name,"last_name":request.user.last_name,}
        user = get_object_or_404(User, username=username)
        form = self.form_class(instance=request.user.profile, initial = initial_dict)
        return render(request, self.template_name, {'user':user, 'form':form})
    
    def post(self, request, *args, **kwargs):
        initial_dict = {"email" : request.user.email,"first_name" : request.user.first_name,"last_name":request.user.last_name,}
        form = self.form_class(request.POST, request.FILES, instance=request.user.profile, initial = initial_dict)
        if form.is_valid():
            print(form.cleaned_data['email'])
            newform = form.save(commit=False)
            newform.user = request.user
            newform.save()
            request.user.email = form.cleaned_data['email']
            request.user.first_name = form.cleaned_data['first_name']
            request.user.last_name = form.cleaned_data['last_name']
            request.user.save()
            messages.success(request, 'your personal info has been updated', 'info')
            return redirect('accounts:dashboard', request.user.username)
        return render(request, self.template_name, {'form':form})

class RemovePhotoView(LoginRequiredMixin, View):
    template_name = 'accounts/dashboard.html'
    def get(self, request):
        user = request.user
        profile = get_object_or_404(Profile, user=user)
        profile.photo.delete()
        return redirect('accounts:dashboard', request.user)

#All view that user need to send pin and create board
class UserPins(LoginRequiredMixin, View):
    template_name = 'accounts/user_pins.html'

    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        userpins = Pin.objects.filter(user=user)
        return render(request, self.template_name, {'userpins':userpins})


class NewPinView(LoginRequiredMixin,View):
    template_name = 'accounts/new_pin.html'
    form_class = PinForm

    def get(self, request, username):
        form = self.form_class
        return render(request, self.template_name, {'form':form})

    def post(self, request, username=None):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.user = request.user
            newpost.slug = newpost.id
            newpost.save()
            messages.success(request, 'your new post created successfully', 'info')
            return redirect("accounts:user_pins", request.user)
        return render(request, self.template_name, {'form':form})

class DeletePinView(LoginRequiredMixin, View):
    def get(self, request, id=None):
        pin = get_object_or_404(Pin, id=id)
        if pin.user.username == request.user.username:
            pin.delete()
        else:
            messages.warning(request, 'you are not allow to delete this pin', 'info')    
        messages.success(request, 'your pin has been deleted successfully', 'info')
        return redirect("accounts:user_pins", request.user)

class UserBoards(LoginRequiredMixin, View):
    template_name = 'accounts/user_boards.html'

    def get(self, request, username):
        user = get_object_or_404(User, username=username)
        boards = Board.objects.filter(user=user).order_by('-created')
        return render(request, self.template_name, {'boards':boards})

class CreateBoardView(LoginRequiredMixin,View):
    template_name = 'accounts/new_board.html'
    form_class = BoardForm

    def get(self, request, username):
            form = self.form_class
            return render(request, self.template_name, {'form':form})

    def post(self, request, username=None):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.user = request.user
            newpost.slug = newpost.id
            newpost.save()
            messages.success(request, 'your new board created successfully', 'info')
            return redirect("accounts:user_boards", request.user.username)
        return render(request, self.template_name, {'form':form})


class BoardView(DetailView):
    template_name = 'board_detail.html'
    context_object_name = 'board'
    queryset = Board.objects.all()

#all view that required for follow and unfollow for users
class FollowView(LoginRequiredMixin, View):
    def post(self, request):
        user_id = request.POST['user_id']
        following = get_object_or_404(User, pk=user_id)
        check_relation = UsersRelation.objects.filter(from_user=request.user, to_user=following)
        if check_relation.exists():
            return JsonResponse({'status':'exists'})
        else:
            UsersRelation.objects.create(from_user=request.user, to_user=following)
            return JsonResponse({'status':'ok'})


class UnfollowView(LoginRequiredMixin, View):
    def post(self, request):
        user_id = request.POST['user_id']
        following = get_object_or_404(User, pk=user_id)
        check_relation = UsersRelation.objects.filter(from_user=request.user, to_user=following)
        if check_relation.exists():
             check_relation.delete()
             return JsonResponse({'status':'ok'})
        else:
            return JsonResponse({'status':'notexists'})

class QuickSaveView(LoginRequiredMixin, View):
    template_name = 'pin_list.html'

    def get(self, request, id=None):
        user = get_object_or_404(User, id=request.user.id)
        pin = get_object_or_404(Pin, id=id)
        quicksave_pin = QuickSave.objects.filter(pin=pin)
        if len(quicksave_pin) > 0:
            quicksave_pin[0].user.add(user)
            return redirect("pin:listpin")
        else:
            q_save = QuickSave.objects.create(pin=pin)
            q_save.user.add(user)
            q_save.save()
            return redirect("pin:listpin")
        
        return render(request, self.template_name)
    def post(self, request):
        pass

class RemoveQuickSaveView(View):
    def get(self, request, id=None):
        user = get_object_or_404(User, id=request.user.id)
        pin = get_object_or_404(Pin, id=id)
        quicksave_pin = QuickSave.objects.get(pin=pin)
        quicksave_pin.user.remove(user)
        return redirect("pin:listpin")

templates/accounts/dashboard.html
{% extends "base.html" %}

{% block content %}

<div class="row justify-content-md-center mt-5">
  <div class="col-5">
    <div class="card p-4 shadow-sm border-0">

      <h5 class="">
        {{user}}
        {% if request.user == user %}
        <a href="{% url 'accounts:update_profile' request.user %}" class="btn btn-primary btn-sm float-end"><i
            class="bi bi-pencil-square"></i></a>
        {% else %}
        <!-- check request.user is follow user or not -->
        {% if request.user.is_authenticated %}
        {% if not is_following %}
        <button id="following_btn" class="btn btn-primary btn-sm float-end" data-id="{{ user.id }}"><i
            class="bi bi-node-plus"></i> Follow</button>
        {% else %}
        <button id="following_btn" class="btn btn-warning btn-sm float-end" data-id="{{ user.id }}"><i
            class=" bi bi-check"></i> Following</button>
        {% endif %}
        {% endif %}
        <!-- end check request.user is follow user or not -->
        {% endif %}
      </h5>
      <hr>
      <h5 class="">
      <div class="row">
      <div class="col text-center">Pins: {{userpins.count}}</div>
      <div class="col text-center">Followers: {{followers.count}}</div>
      <div class="col text-center">Following: {{following.count}}</div>
      </div>
      </h5>
      <div class="card-body">

        <div class="row mt-3">
          <div class="col-8">

            <table class="table">
              <tbody>
                <tr>
                  <td>Name</td>
                  {% if user.first_name or user.last_name %}
                  <td>{{user.first_name}} {{user.last_name}}</td>
                  {% else %}
                  <td>---</td>
                  {% endif %}
                </tr>
                <tr>
                  <td>Email</td>
                  <td>{{user.email}}</td>
                </tr>
                <tr>
                  <td>Age</td>
                  {% if user.profile.age %}
                  <td>{{user.profile.age}} years old</td>
                  {% else %}
                  <td>---</td>
                  {% endif %}
                </tr>
                <tr>
                  <td>Bio</td>
                  {% if user.profile.bio %}
                  <td>{{user.profile.bio}}</td>
                  {% else %}
                  <td>---</td>
                  {% endif %}
                </tr>
              </tbody>
            </table>
          </div>
          <div class="col-4">
            {% if user.profile.photo %}
            <div class="profileimg">
              <img src="{{ user.profile.photo.url }}" class="img-thumbnail rounded float-end" alt="...">
              {% if request.user == user %}
              <a href="{% url 'accounts:remove_photo' %}"><i class="bi bi-x-square-fill"></i></a>
              {% endif %}
            </div>
            {% else %}
            <i class="bi bi-person-bounding-box float-end" style="font-size:8rem;color:#6d6d6d"></i>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

<div class="row justify-content-md-center mt-5">
    <div class="col-4">
        <div class="card shadow-sm p-4 border-0">
        <h5 class=""><i class="bi bi-box-arrow-in-left"></i> Sign in to PinoBino</h5>
        <hr>
        <div class="card-body">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {{form.non_fields_errors}}
                
                <label for="{{ form.username.id_for_label}}" class="pb-1"><i class="bi bi-file-person"></i> Username</label>
                {{form.username.errors}}
                {{form.username}}

                <label for="{{ form.password.id_for_label}}" class="pb-1"><i class="bi bi-key"></i> Password</label>
                {{form.password.errors}}
                {{form.password}}
                
                <button type="submit" class="btn btn-primary mt-2"><i class="bi bi-check"></i> Login</button>
            </form>
        </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/new_board.html
{% extends 'base.html' %}


{% block content %}
<div class="row justify-content-md-center mt-5">
    <div class="col-5">
        <div class="card">
            <h5 class="card-header"><i class="bi bi-plus-square"></i> Create new board</h5>
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    {{form.non_fields_errors}}

                    <label for="{{ form.title.id_for_label}}" class="pb-1"><i class="bi bi-card-heading"></i>
                        Title</label>
                    {{form.title.errors}}
                    {{form.title}}

                    <label for="{{ form.description.id_for_label}}" class="pb-1"><i class="bi bi-text-left"></i>
                        Description</label>
                    {{form.description.errors}}
                    {{form.description}}

                    <button type='submit' class="btn btn-primary"><i class="bi bi-save"></i> Create</button>
                    <a href="{% url 'accounts:user_boards' request.user %}" class="btn btn-secondary"><i
                            class="bi bi-x-square"></i> Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/new_pin.html
{% extends 'base.html' %}


{% block content %}
<div class="row justify-content-md-center mt-5">
    <div class="col-5">
        <div class="card p-4 shadow-sm border-0">
            <h5 class=""><i class="bi bi-plus-square"></i> Send new pin image</h5>
            <hr>
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}

                    {{form.non_fields_errors}}

                    <label for="{{ form.title.id_for_label}}" class="pb-1"><i class="bi bi-card-heading"></i>
                        Title</label>
                    {{form.title.errors}}
                    {{form.title}}

                    <label for="{{ form.board.id_for_label}}" class="pb-1"><i class="bi bi-file-person"></i>
                        Board</label>
                    {{form.board.errors}}
                    {{form.board}}

                    <label for="{{ form.image.id_for_label}}" class="pb-1"><i class="bi bi-card-image"></i>
                        Photo</label>
                    {{form.image.errors}}
                    {{form.image}}

                    <label for="{{ form.url.id_for_label}}" class="pb-1"><i class="bi bi-link-45deg"></i>
                        URL</label>
                    {{form.url.errors}}
                    {{form.url}}

                    <label for="{{ form.caption.id_for_label}}" class="pb-1"><i class="bi bi-card-text"></i>
                        Caption</label>
                    {{form.caption.errors}}
                    {{form.caption}}

                    <button type='submit' class="btn btn-primary"><i class="bi bi-save"></i> Save</button>
                    <a href="{% url 'accounts:user_pins' request.user %}" class="btn btn-secondary"><i
                            class="bi bi-x-square"></i> Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-md-center mt-5">
    <div class="col-4">
        <div class="card shadow-sm p-4 border-0">
        <h5 class=""><i class="bi bi-person-plus"></i> Sign up to PinoBino</h5>
        <hr>
        <div class="card-body">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {{form.non_fields_errors}}
                
                <label for="{{ form.username.id_for_label}}" class="pb-1"><i class="bi bi-file-person"></i> Username</label>
                {{form.username.errors}}
                {{form.username}}

                <label for="{{ form.email.id_for_label}}" class="pb-1"><i class="bi bi-envelope"></i> Email</label>
                {{form.email.errors}}
                {{form.email}}

                <label for="{{ form.password.id_for_label}}" class="pb-1"><i class="bi bi-card-text"></i> Password</label>
                {{form.password.errors}}
                {{form.password}}

                <button type="submit" class="btn btn-primary mt-2"><i class="bi bi-check"></i> Register</button>
            </form>
        </div>
        </div>
    </div>
</div>




{% endblock content %}

templates/accounts/update_profile.html
{% extends "base.html" %}

{% block content %}

<div class="row justify-content-md-center mt-5">
    <div class="col-5">
        <div class="card p-4 shadow-sm border-0">
            {% if user.first_name or user.last_name %}
            <h5 class="">
                {{user.first_name}} {{user.last_name}}
            </h5>
            {% else %}
            <h5 class="">
                {{user.username}}
            </h5>
            <hr>
            {% endif %}
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}

                    <label for="{{ form.photo.id_for_label}}" class="pb-1"><i class="bi bi-person-bounding-box"></i>
                        Photo</label>
                    {{form.photo.errors}}
                    {{form.photo}}

                    <label for="{{ form.first_name.id_for_label}}" class="pb-1"><i class="bi bi-person"></i> First
                        Name</label>
                    {{form.first_name.errors}}
                    {{form.first_name}}

                    <label for="{{ form.last_name.id_for_label}}" class="pb-1"><i class="bi bi-person"></i> Last
                        Name</label>
                    {{form.last_name.errors}}
                    {{form.last_name}}

                    <label for="{{ form.email.id_for_label}}" class="pb-1"><i class="bi bi-envelope"></i> Email</label>
                    {{form.email.errors}}
                    {{form.email}}

                    <label for="{{ form.age.id_for_label}}" class="pb-1"><i class="bi bi-file-bar-graph"></i>
                        Age</label>
                    {{form.age.errors}}
                    {{form.age}}

                    <label for="{{ form.bio.id_for_label}}" class="pb-1"><i class="bi bi-card-text"></i> Bio</label>
                    {{form.bio.errors}}
                    {{form.bio}}

                    <button type='submit' class="btn btn-primary"><i class="bi bi-save"></i> Save</button>
                    <a href="{% url 'accounts:dashboard' request.user %}" class="btn btn-secondary"><i
                            class="bi bi-x"></i> Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

templates/accounts/user_boards.html
{% extends "base.html" %}

{% block content %}

<div class="row justify-content-md-center mt-5">
  <div class="col-6">
    <div class="card p-4 shadow-sm border-0">
      <h5 class="">
        Boards: {{boards.count}} board
        <a href="{% url 'accounts:newboard' request.user %}" class="btn btn-primary btn-sm float-end"><i
            class="bi bi-plus-square"></i> New</a>
      </h5>
      <hr>
      <div class="card-body">
        <div class="row">
          {% for board in boards %}
          <div class="col-12 mt-3">
            <div class="card shadow-sm">
              <div class="card-body">
                <div class="row">
                  <div class="col-9">
                    <h5 class="card-title">{{board.title}}</h5>
                    <span class="card-text">{{board.description}}</span>
                  </div>
                  <div class="col-3">
                    <a href="#" class="btn btn-primary btn-sm m-1"><i class="bi bi-pencil-square"></i></a>
                    <i class="bi bi-grip-vertical"></i>
                    <a href="#" class="btn btn-danger btn-sm m-1"><i class="bi bi-trash"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% empty %}
          <p>You do not have a board right now .You can make a board and categorize your pins</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/accounts/user_pins.html
{% extends "base.html" %}

{% block content %}

<div class="row justify-content-md-center mt-5">
  <div class="col-6">
    <div class="card p-4 shadow-sm border-0">
      <h5 class="">
        Pins : {{userpins.count}} pin
      </h5>
      <hr>
      <div class="card-body">
        <div class="row">
          {% for pin in userpins %}
          <div class="col-4 mt-3">
            <div class="card h-100">
              <a href="{% url 'pin:single_pin' pin.slug%}">
                <img src="{{pin.image.url}}" class="card-img-top" alt="">
              </a>
              <div class="card-body">
                <p class="card-text">{{pin.caption|truncatechars:20}}</p>
              </div>
              <div class="card-footer">
                <a href="{% url 'accounts:delete_pin' pin.id %}" class="btn btn-danger btn-sm">
                  <i class="bi bi-trash"></i>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}