accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'
urlpatterns = [
    path('singup/', views.UserRegister.as_view(), name='register'),
    path('singin/', views.UserLogin.as_view(), name='login'),
    path('singout/', views.UserLogout.as_view(), name='logout'),
    path('profile/<str:username>', views.UserDashboard.as_view(), name='dashboard'),
    path('dashboard/<str:username>/update/', views.UpdateUserProfile.as_view(), name='update_profile'),
    path('dashboard/<str:username>/pins', views.UserPins.as_view(), name='user_pins'),
    path('dashboard/pin/delete/<str:id>', views.DeletePinView.as_view(), name='delete_pin'),
    path('dashboard/<str:username>/newpin/', views.NewPinView.as_view(), name='new_pin'),
    path('dashboard/<str:username>/boards', views.UserBoards.as_view(), name='user_boards'),
    path('dashboard/<str:username>/newboard/', views.CreateBoardView.as_view(), name='newboard'),
    path('dashboard/photo/remove/' , views.RemovePhotoView.as_view(), name='remove_photo'),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('unfollow/', views.UnfollowView.as_view(), name='unfollow'),
    path('quicksave/<str:id>', views.QuickSaveView.as_view(), name='quicksave'),
    path('quicksave/remove/<str:id>', views.RemoveQuickSaveView.as_view(), name='remove_quicksave'),
    path('addtoboard/<str:pinid>/<str:boardid>', views.AddPinToBoard.as_view(), name='addtoboard'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pin.urls', namespace='pin')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pin/urls.py
from django.urls import path
from . import views

app_name = 'pin'

urlpatterns = [
    path('', views.PinsListView.as_view(), name='listpin'),
    path('pin/<slug:slug>/', views.PinView.as_view(), name='single_pin'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}PinoBino{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/mainstyle.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
     <style>
        .dropdown-toggle::after {
            content: none;
        }
    </style>
</head>

<body>
    {% include 'inc/navbar.html' %}
    {% include 'inc/search.html' %}
    {% include 'inc/messages.html' %}
    <div id="overlay"></div>
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>


    <script>
        const data = "{{qs_json}}"
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src={% static 'js/jquery.min.js' %}></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
        integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D" crossorigin="anonymous"
        async></script>
    <script src={% static 'js/mainjs.js' %} type="text/javascript"></script>
    <script>
        $('#following_btn').click(function () {
            var user_id = $('#following_btn').attr('data-id')
            var follow = $('#following_btn').html()

            var follow_html = '<i class="bi bi-node-plus"></i> Follow'
            var following_html = '<i class="bi bi-check"></i> Following'

            if (follow == follow_html) {
                var url = '/accounts/follow/'
                var btn_text = following_html
                var btn_class = 'btn btn-warning btn-sm float-end'

            } else {
                var url = '/accounts/unfollow/'
                var btn_text = follow_html
                var btn_class = 'btn btn-primary btn-sm float-end'
            }

            $.ajax({
                url: url,
                headers: {
                    "X-CSRFToken": '{{csrf_token}}'
                },
                method: 'POST',
                data: {
                    'user_id': user_id,
                },
                success: function (data) {
                    if (data['status'] == 'ok') {
                        $('#following_btn').html(btn_text)
                        $('#following_btn').attr({
                            'class': btn_class
                        })
                    }
                }
            });

        });
    </script>
</body>

</html>

templates/pin_detail.html
{% extends 'base.html' %}


{% block content %}

<div class="row justify-content-md-center mt-5">
  <div class="col-6">
    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-4">
          <img class="card-img" src="{{pin.image.url}}" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">

            {% if pin.user.profile.photo %}
            <div class="mt-1 mb-3">
              <img src="{{ pin.user.profile.photo.url }}" class="ms-1 pe-1 rounded-circle img-responsive" style='width:5%' alt="...">
              <a href="{% url 'accounts:dashboard' pin.user %}" class="link-dark"
                style='text-decoration:none'>{{pin.user}}
              </a>
            </div>
            {% else %}
            <div class="mt-1 mb-3">
              <i class="ms-1 pt-2 bi bi-person-bounding-box"></i>
              <a href="{% url 'accounts:dashboard' pin.user %}" class="pt-2 pt-2 link-dark"
                style='text-decoration:none'>{{pin.user}}
              </a>
            </div>
            {% endif %}

            <p class="card-text">{{pin.caption}}</p>
            <p class="card-text"><small class="text-muted">Uploaded {{pin.created|timesince}} ago</small></p>
            <a href="#" class="btn btn-outline-secondary btn-sm bottom-0">
              <i class="bi bi-journal-album"></i> {{pin.board}}
            </a>
            <a href="{% url 'pin:listpin'%}" class="position-absolute top-0 end-0 mt-1" style="margin-right:5px;">
              <h3><i class="bi bi-x-circle text-secondary"></i></h3>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/pin_list.html
{% extends 'base.html' %}


{% block content %}
<div class="row row-cols-1 row-cols-sm-3 row-cols-md-6 row-cols-lg-8 g-3 mt-4 mb-4"
  data-masonry='{"percentPosition": true }'>
  {% for pin in pins %}
  <div class="border-0">
    <div class="pin_image">
      <a href="{% url 'pin:single_pin' pin.slug%}">
        <img src="{{pin.image.url}}" class="card-img-top rounded-3" alt="">
      </a>
      {% if request.user.is_authenticated %}
      <div class="btn-group" id="addtosave">
        <button type="button" class="btn btn-dark btn-sm dropdown-toggle" data-bs-toggle="dropdown"
          data-bs-display="static" aria-expanded="false">
          <i class="bi bi-plus-square"></i> Add to Boards
        </button>
        <ul class="dropdown-menu">
          {% for board in user_boards %}
          <li><a href="{% url 'accounts:addtoboard' pin.id board.id %}" class="dropdown-item" type="button">{{board.title}}</a></li>
          {% endfor %}
        </ul>
      </div>


      {% if pin.id in user_pin_save %}
      <a href="{% url 'accounts:remove_quicksave' pin.id %}"><i class="bi bi-save-fill" id="quicksave"
          data-bs-toggle="tooltip" data-bs-placement="bottom" title="Unsave"></i></a>
      {% else %}
      <a href="{% url 'accounts:quicksave' pin.id %}"><i class="bi bi-save" id="quicksave" data-bs-toggle="tooltip"
          data-bs-placement="bottom" title="Save"></i></a>
      {% endif %}
      {% endif %}
    </div>
    {% if pin.user.profile.photo %}
    <div class="mt-1">
      <img src="{{ pin.user.profile.photo.url }}" class="ms-1 pe-1" style='width:10%' alt="...">
      <a href="{% url 'accounts:dashboard' pin.user %}" class="link-dark" style='text-decoration:none'>{{pin.user}}
      </a>
    </div>
    {% else %}
    <div class="mt-1">
      <i class="ms-1 pt-2 bi bi-person-bounding-box"></i>
      <a href="{% url 'accounts:dashboard' pin.user %}" class="pt-2 pt-2 link-dark"
        style='text-decoration:none'>{{pin.user}}
      </a>
    </div>
    {% endif %}
    {% comment %} <div class="card-body">
      <h5 class="card-title">
        {% if user.profile.photo %}
        <small><img src="{{ pin.user.profile.photo.url }}" class="img-thumbnail rounded" alt="..."><a
            href="{% url 'accounts:dashboard' pin.user %}">{{pin.user}}</a></small>
        {% else %}
        <small><i class="bi bi-person-bounding-box"></i> <a
            href="{% url 'accounts:dashboard' pin.user %}">{{pin.user}}</a></small>
        {% endif %}
      </h5>
    </div>
    <div class="card-footer">
      <small><i class="bi bi-journal-album"></i> {{pin.board}}</small>
      <a href="{% url 'pin:single_pin' pin.slug%}" class="float-end"><i class="bi bi-three-dots"></i> </a>
    </div> {% endcomment %}
  </div>
  {% endfor %}
</div>

{% endblock content %}