accounts/urls.py
from django.urls import path
from . import views



app_name = 'accounts'
urlpatterns = [
    path('singup/', views.UserRegister.as_view(), name='register'),
    path('singin/', views.UserLogin.as_view(), name='login'),
    path('singout/', views.UserLogout.as_view(), name='logout'),
    path('profile/<str:username>', views.UserDashboard.as_view(), name='dashboard'),
    path('dashboard/<str:username>/update/', views.UpdateUserProfile.as_view(), name='update_profile'),
    path('dashboard/<str:username>/pins', views.UserPins.as_view(), name='user_pins'),
    path('dashboard/pin/delete/<str:id>', views.DeletePinView.as_view(), name='delete_pin'),
    path('dashboard/<str:username>/newpin/', views.NewPinView.as_view(), name='new_pin'),
    path('dashboard/<str:username>/boards', views.UserBoards.as_view(), name='user_boards'),
    path('dashboard/<str:username>/newboard/', views.CreateBoardView.as_view(), name='newboard'),
    path('dashboard/photo/remove/' , views.RemovePhotoView.as_view(), name='remove_photo'),
    path('follow/', views.FollowView.as_view(), name='follow'),
    path('unfollow/', views.UnfollowView.as_view(), name='unfollow'),
    path('quicksave/<str:id>', views.QuickSaveView.as_view(), name='quicksave'),
    path('quicksave/remove/<str:id>', views.RemoveQuickSaveView.as_view(), name='remove_quicksave'),
    path('addtoboard/<str:pinid>/<str:boardid>', views.AddPinToBoard.as_view(), name='addtoboard'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pin.urls', namespace='pin')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pin/urls.py
from django.urls import path
from . import views

app_name = 'pin'

urlpatterns = [
    path('', views.PinsListView.as_view(), name='listpin'),
    path('pin/<slug:slug>/', views.PinView.as_view(), name='single_pin'),
]

templates/inc/messages.html
{% comment %} {% if messages %}
    {% for message in messages %}
        <p {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</p>
    {% endfor %}
{% endif %} {% endcomment %}

  {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script type=text/javascript>toastr.{{ message.tags }}{{ message }}</script>
            {% elif message.tags == 'info' %}
                <script type=text/javascript>toastr.{{ message.tags }}{{ message }}</script>
            {% elif message.tags == 'warning' %}
                <script type=text/javascript>toastr.{{ message.tags }}{{ message }}</script>
            {% elif message.tags == 'error' %}
                <script type=text/javascript>toastr.{{ message.tags }}{{ message }}</script>
            {% endif %}
        {% endfor %}
    {% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <ul class="navbar-nav">
      <a class="navbar-brand" href="#">PinoBino</a>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="/">Home</a>
      </li>
    </ul>
    <div class="input-group input-group-lg d-flex w-50">
      <input type="text" class="form-control" id="searchbar" aria-label="Sizing example input"
        aria-describedby="inputGroup-sizing-lg">
      <span class="input-group-text" id="inputGroup-sizing-lg"><i class="bi bi-search"></i></span>
    </div>
    <ul class="navbar-nav">
      <!-- new pin for authenticated users -->
      {% if request.user.is_authenticated %}
      <a href="{% url 'accounts:new_pin' request.user %}" class="btn btn-danger float-end">
        <svg xmlns="http://www.w3.org/2000/svg" width="25" height="20" fill="currentColor" class="bi bi-plus-lg"
          viewBox="0 0 14 18">
          <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z" />
        </svg>
      </a>
      {% endif %}
      <!-- new pin for authenticated users -->
      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown float-right">
        <a class="nav-link dropdown-toggle" href="#" id="usersetting_dropdown" role="button" data-bs-toggle="dropdown"
          aria-expanded="false">

          {% if request.user.profile.photo %}
          <img src="{{request.user.profile.photo.url}}" class="rounded" alt="..." width="25em">
          {% else %}
          <i class="bi bi-person-bounding-box"></i>
          {% endif %}

          {% if request.user.first_name %}
          {{request.user.first_name}}
          {% else %}
          {{request.user}}
          {% endif %}
        </a>
        <ul class="dropdown-menu dropdown-menu-end border-0 shadow-sm p-2" aria-labelledby="navbarDropdownMenuLink">
          <li>
            <a class="dropdown-item" href="{% url 'accounts:dashboard' request.user %}">
              <i class="bi bi-file-person"></i> Profile
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'accounts:update_profile' request.user %}"><i
                class="bi bi-pencil-square"></i> Account Settings
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'accounts:user_pins' request.user %}">
              <i class="bi bi-pin-angle"></i> Pins
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'accounts:user_boards' request.user %}">
              <i class="bi bi-journal-album"></i> Boards
            </a>
          </li>
          <li>
            <hr>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">
              <i class="bi bi-box-arrow-right"></i> Sign out
            </a>
          </li>
        </ul>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'accounts:login' %}"><i class="bi bi-box-arrow-in-left"></i> Sign in</a>
      </li>
      <li class="nav-item">
        <a class="nav-link btn btn-primary" style="color:white" href="{% url 'accounts:register' %}"><i
            class="bi bi-person-plus"></i> Sign up</a>
      </li>
      {% endif %}
      <ul>
  </div>
</nav>

templates/inc/search.html
<div class="w-66" id="search-board" style="display:none">
</div>